### ISSUE TITLE
Heroku provisioning fails due to SendGrid missmatch 

### ISSUE THREAD

**Issue by osowskit** [gjtorikian/probot-messenger#8]
The current Heroku deployment returns an error `sendgrid add-ons can only be attached as SENDGRID.`. Modifying this line to use `SENDGRID` resolves this:

https://github.com/gjtorikian/probot-emailer/blob/26125d666ebf5a92656f38cb8b0ea1aa5dbd2626/app.json#L15

**Comment by gjtorikian** [comment]
Care to make a PR? :trollface:

**Comment by osowskit** [comment]
Yep. Logged it so I wouldn't forget.
